name: Model Evaluation

on:
  push:
    branches: [ main, release/* ]
    paths:
      - 'datasets/**'
      - 'models/**'
      - 'adapters/**'
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      dataset:
        description: 'Dataset path (relative to repository root)'
        required: true
        default: 'datasets/'
      model:
        description: 'Model name or path'
        required: true
        default: 'mock'

jobs:
  evaluate:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install matplotlib pandas seaborn
        
    - name: Run evaluation
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
      run: |
        python run_eval.py \
          --dataset "${{ github.event.inputs.dataset || 'datasets/' }}" \
          --model "${{ github.event.inputs.model || 'mock' }}" \
          --output "outputs/results_$(date +%Y%m%d_%H%M%S).csv"
          
    - name: Run post-analysis
      run: |
        python deepseek_post_analysis.py
        
    - name: Generate visualizations
      run: |
        python visualization/generate_plots.py
        
    - name: Upload results
      uses: actions/upload-artifact@v3
      with:
        name: evaluation-results
        path: |
          outputs/*.csv
          deepseek_analysis.log
          visualization/*.png
          
    - name: Create summary comment
      if: github.event_name == 'pull_request'
      uses: mshick/add-pr-comment@v2
      with:
        message: |
          ## Evaluation Results
          
          ### Summary
          $(cat deepseek_analysis.log | grep -A 10 "Deepseek Analysis Summary")
          
          ### Visualizations
          ![Success Rate](visualization/success_rate.png)
          
          Full results available in the artifacts.
