name: Generate Logo

on:
  push:
    paths:
      - 'scripts/generate_logo.py'
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  generate-logo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pillow
          
      - name: Generate logo
        run: |
          mkdir -p assets
          python scripts/generate_logo.py
          
      - name: Commit and push changes
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop'
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add assets/logo.png
          git diff --quiet && git diff --staged --quiet || \
            (git commit -m "chore: update generated logo" && git push)
